<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Get_MyProject_BOOKS"
                  name="Get_MyProject_BOOKS-concrete" 
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
                  
  <wsdl:import location="Get_MyProject_BOOKS.wsdl"
               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Get_MyProject_BOOKS"/>
               
  <wsdl:binding name="Get_MyProject_BOOKS_ptt-binding" type="get:Get_MyProject_BOOKS_ptt"
                xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/top/Get_MyProject_BOOKS">
                
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    
    <wsdl:operation name="Get_MyProject_BOOKSSelect">
      <soap:operation soapAction="Get_MyProject_BOOKSSelect"/>
      
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>