<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/KPMGBIMApplication/MyProject_Export/MyProjectBatchPooler"
                  name="MyProjectBatchPooler-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
                  
  <wsdl:import location="MyProjectBatchPooler.wsdl"
               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/KPMGBIMApplication/MyProject_Export/MyProjectBatchPooler"/>
               
  <wsdl:binding name="MyProjectBatchPooler_ptt-binding" type="myp:MyProjectBatchPooler_ptt"
                xmlns:myp="http://xmlns.oracle.com/pcbpel/adapter/db/KPMGBIMApplication/MyProject_Export/MyProjectBatchPooler">
                
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    
    <wsdl:operation name="receive">
      <soap:operation soapAction="receive"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    
  </wsdl:binding>
  
</wsdl:definitions>